#!/bin/bash

echo 'Starting Google Photos backup'
/home/tim/bin/goLibs/rclone $1 --transfers 8 --retries 99 --modify-window 5s --drive-upload-cutoff 5M -c --config /home/tim/.rclone.conf sync GDrive:Google\ Photos/ /backups/googlePhotos/
