#!/bin/bash

cd /home/tim/bin/gphotos-sync/
source ./bin/activate
gphotos-sync /backups/googlePhotos/
deactivate
exit

## For python upgrades, new venv must be created


## rm -rf ~/bin/gphotos-sync-old; mv ~/bin/gphotos-sync ~/bin/gphotos-sync-old; 
## python3.10 -m venv ~/bin/gphotos-sync ; cd ~/bin/gphotos-sync/; . ~/bin/activate ; pip install gphotos-sync

