#!/bin/bash

## Disable middle monitor, sleep for 5 sec allowing PS4 to take control, re-setup middle monitor
xrandr --output DVI-0 --off

sleep 5s

xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0       --rotate left \
           --output DVI-0 --mode 1920x1080 --pos 1080x0 --rotate normal \
           --output DVI-1 --mode 1920x1080 --pos 3000x0    --rotate normal

