#!/bin/bash


## grabsite by $1 specified

USER_AGENT="Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)"
SAVE_HOST="$1"
WARC_NAME="$2"
DATE_NOW=`date +%F`

echo ""
echo "---------- INFO -----------"
echo ""
echo "USER_AGENT is " $USER_AGENT
echo "SAVE_HOST is " $SAVE_HOST
echo "DATE_NOW is " $DATE_NOW
echo "WARC File name will be $SAVE_HOST-$DATE_NOW"
echo ""
echo "----------- GRABBING ---------"
echo ""

wget -e robots=off --mirror --page-requisites --waitretry 5 --timeout 60 --tries 5 --wait 2 --warc-header "operator: Archive Team" --warc-cdx --warc-file="$SAVE_HOST-$DATE_NOW" -U "$USER_AGENT" "$SAVE_HOST"

echo ""
echo "---- GRAB FINISHED ----"
echo ""
