#!/bin/bash

# Smiley strikes again with another scary script
#
# Script designed to use the pages of xanga groups to return xanga webpages; then grep those pages for usernames contained within the xanga url (the username in the url maybe different to
# the username as printed on the site
#
# grep, awk and wget#
#
# 0.1.5
#
# 21/06/2013 

for y in $(eval echo "{$1..$2}"); # highest ID found via searching the site manually - IF HELPING SET VALUES HERE
	do wget -a wget.log -O test "http://www.xanga.com/groups/subdir.aspx?id=$y&uni-72-pg=1";  # Grab first page
	max_pages=$(grep "pagenav-next" -B 1 ./test | awk -F= '{print $5}' | awk -F\> '{print $1}' | awk -F\" '{ print $1}' | head -n 1);
	echo "Got value for group $y; Max pages = $max_pages";
	echo "grabbing pages 1 - $max_pages";
	for x in $(eval echo "{1..$max_pages}")			## So bash is broken! Who knew! (can't use: {1..$max_pages}; ) 
		do
		echo "Grabbing page $x of $max_pages";
		wget -v --directory-prefix=_$y -a wget.log "http://www.xanga.com/groups/subdir.aspx?id=$y&uni-72-pg=$x"; 
		sleep 0.1;
	done;
done




### grep "created by" -r ./* | awk -F "<" '{print $3}' | awk -F\/ '{print $3}' | awk -F. '{ print $1}' | sort -u  ### Pull out usernames once done
