#!/bin/sh 
#
# Script to mail top processes called by nagios event handlers
#
# Will send to address below
#
# $1 = state passed by nagios
#################################################################

EMAILTO="a@b.com"
SUBJECT="Alert Raised - Process report on $HOSTNAME"
date_now="`date +%s`"

# Check for timestamp file and load, if not default to 'now'

if [ -e /tmp/timestamp ]
then
	TS="`cat /tmp/timestamp`"
#	echo "timestamp found"
else
	TS=$(($date_now+1800))
	override="1"
#	echo "timestamp not found; Updating" && echo $TS > /tmp/timestamp
fi

#echo "TS is $TS"
#echo "date_now is $date_now"


gen_mail (){ /bin/ps -eo pid,comm,%cpu | /bin/sort -rk 3
}


mail_mail (){ /bin/mail -s "$1" "$2" 
}

# Start the script!

if [[ "$TS" -le "$date_now" || "$override" -eq "1" ]]
then
	#echo "Going ahead"
	goahead="1"
else
	#echo "not going ahead"
	goahead="0" 
fi



# Debugging line
# echo "\$1 is " $1


	if [ $goahead = "1" ]
		then
		case "$1" in

		WARNING)

			# Warning level -  top 10 processes
			 gen_mail | /usr/bin/head -n 10 | mail_mail "$SUBJECT" "$EMAILTO"
			echo $(($date_now+1800)) > /tmp/timestamp
			;;

		CRITICAL)

			# Critical level - passing all processes
			gen_mail | mail_mail "$SUBJECT" "$EMAILTO"
			echo $(($date_now+1800)) > /tmp/timestamp
			;;

		esac
	fi

	exit

